# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Test Deploy Catalog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build the app
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Run backend
      run: npm run start-be &
    - name: Wait 5 seconds
      run: sleep 5
    - name: Run FrontEnd
      run: npm run start-fe &
    - name: Wait 5 seconds
      run: sleep 5
    - name: Run tests
      run: npm run test