# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Test Deploy Catalog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build the app
      run: npm install
    - name: Install system libraries for Playwright
      run: sudo apt-get install -y libwoff2dec1 libvpx5 libevent-2.1-7 libopus0 libharfbuzz-icu0 libgstallocators1.0-0 libgstapp1.0-0 libgstpbutils1.0-0 libgstaudio1.0-0 libgsttag1.0-0 libgstvideo1.0-0 libgstgl1.0-0 libgstcodecparsers1.0-0 libgstfft1.0-0 libhyphen0 libmanette-0.2-0 libflite1 libflite_usenglish1 libflite_cmu_grapheme_lang1 libflite_cmu_grapheme_lex1 libflite_cmu_indic_lang1 libflite_cmu_indic_lex1 libflite_cmulex1 libflite_cmu_time_awb1 libflite_cmu_us_awb1 libflite_cmu_us_kal161 libflite_cmu_us_kal1 libflite_cmu_us_rms1 libflite_cmu_us_slt1 libgles2 libx264-152
    - name: Install playwright
      run: npx playwright install
    - name: Run unit tests
      run: npm test
